-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.contrat
(
    id_contrat integer NOT NULL DEFAULT nextval('contrat_id_contrat_seq'::regclass),
    type_ character varying COLLATE pg_catalog."default" NOT NULL,
    "is_fullTime" boolean NOT NULL,
    date_debut date NOT NULL,
    date_fin date,
    periode_fin_essai date NOT NULL,
    remuneration numeric NOT NULL,
    motif character varying COLLATE pg_catalog."default",
    fonction character varying COLLATE pg_catalog."default" NOT NULL,
    statut character varying COLLATE pg_catalog."default" NOT NULL,
    fk_entreprise integer NOT NULL,
    fk_salarie integer NOT NULL,
    CONSTRAINT contrat_pkey PRIMARY KEY (id_contrat)
);

CREATE TABLE IF NOT EXISTS public.entreprise
(
    id_entreprise integer NOT NULL DEFAULT nextval('entreprise_id_entreprise_seq'::regclass),
    nom_entreprise character varying COLLATE pg_catalog."default" NOT NULL,
    prenom_entreprise character varying COLLATE pg_catalog."default" NOT NULL,
    telephone_entreprise numeric NOT NULL,
    rue_entreprise character varying COLLATE pg_catalog."default" NOT NULL,
    cp_entreprise numeric NOT NULL,
    ville_entreprise character varying COLLATE pg_catalog."default" NOT NULL,
    siret numeric NOT NULL,
    raison_sociale character varying COLLATE pg_catalog."default" NOT NULL,
    code_ape character varying COLLATE pg_catalog."default" NOT NULL,
    email_entreprise character varying COLLATE pg_catalog."default" NOT NULL,
    mdp_entreprise character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT entreprise_pkey PRIMARY KEY (id_entreprise),
    CONSTRAINT email_entreprise UNIQUE (email_entreprise)
);

CREATE TABLE IF NOT EXISTS public.salarie
(
    id_salarie integer NOT NULL DEFAULT nextval('"salarie_id_salarié_seq"'::regclass),
    nom_salarie character varying COLLATE pg_catalog."default" NOT NULL,
    prenom_salarie character varying COLLATE pg_catalog."default" NOT NULL,
    telephone_salarie numeric NOT NULL,
    rue_salarie character varying COLLATE pg_catalog."default" NOT NULL,
    cp_salarie numeric NOT NULL,
    ville_salarie character varying COLLATE pg_catalog."default" NOT NULL,
    num_ss character varying COLLATE pg_catalog."default" NOT NULL,
    date_naissance date NOT NULL,
    lieu_naissance character varying COLLATE pg_catalog."default" NOT NULL,
    nom_jeune_fille character varying COLLATE pg_catalog."default",
    email_salarie character varying COLLATE pg_catalog."default" NOT NULL,
    mdp_salarie character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT salarie_pkey PRIMARY KEY (id_salarie),
    CONSTRAINT email_salarie UNIQUE (email_salarie)
);

ALTER TABLE IF EXISTS public.contrat
    ADD CONSTRAINT contrainte_fk_entreprise FOREIGN KEY (fk_entreprise)
    REFERENCES public.entreprise (id_entreprise) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.contrat
    ADD CONSTRAINT fk_contrainte_salarie FOREIGN KEY (fk_salarie)
    REFERENCES public.salarie (id_salarie) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;